version: 2.1
executors:
  my-custom-executor:
    docker:
      - image: cimg/node
        auth:
          # ensure you have first added these secrets
          # visit app.circleci.com/settings/project/github/drjoeycadieux/team-litho/environment-variables
          username: $DOCKER_HUB_USER
          password: $DOCKER_HUB_PASSWORD
jobs:
  team-litho:

    executor: my-custom-executor
    steps:
      - checkout
      - run: |
          # echo Hello, World!

workflows:
  my-custom-workflow:
    jobs:
      - team-litho